# Generated by Django 2.2.1 on 2019-10-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
